import os
import subprocess
import time

def run_command(command):
    subprocess.run(command, shell=True)

def main():
    os.system('echo " "')
    time.sleep(4)
    print("Đang tải lệnh")
    time.sleep(2)
    print("Đang update hệ thống")
    time.sleep(1)
    os.system('clear')
    run_command('sudo apt update')
    print("Đang tải Speedtest cho Linux")
    run_command('sudo apt-get install speedtest-cli')
    print("Thành công!")
    os.system('clear')
    print("Đang tải Bios TianoCore")
    time.sleep(1)
    run_command('wget -O bios64.bin "https://github.com/BlankOn/ovmf-blobs/raw/master/bios64.bin"')
    os.system('clear')
    iso_link = input("Nhập liên kết tải file ISO: ")
    run_command(f'wget -O link.iso "{iso_link}"')
    os.system('clear')
    print("Đang tải Ngrok cho Linux")
    time.sleep(1)
    run_command('wget -O ngrok.tgz "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"')
    os.system('clear')
    print("Giải nén và cài đặt")
    run_command('tar -xf ngrok.tgz')
    run_command('rm -rf ngrok.tgz')
    os.system('clear')
    ngrok_token = input("Nhập token Ngrok: ")
    run_command(f'./ngrok authtoken "{ngrok_token}"')
    os.system('clear')
    print("Vui lòng chọn khu vực")
    print("us - Hoa Kỳ (Ohio)")
    print("eu - Châu Âu (Frankfurt)")
    print("ap - Đông Nam Á (Singapore)")
    print("au - Úc (Sydney)")
    print("sa - Nam Mỹ (Sao Paulo)")
    print("jp - Nhật Bản (Tokyo)")
    print("in - Ấn Độ (Mumbai)")
    khuvuc = input("Nhập khu vực: ")
    run_command(f'./ngrok tcp --region {khuvuc} 5900 &>/dev/null &')
    os.system('clear')
    run_command('sudo apt update')
    run_command('sudo apt install qemu-kvm -y')
    run_command('sudo apt install speedtest-cli')
    os.system('clear')
    disk_size = input("Nhập dung lượng ổ đĩa: ")
    run_command(f'qemu-img create -f raw win.img "{disk_size}"')
    time.sleep(1)
    print("Đã tạo ổ đĩa")
    print("Đang gán lệnh")
    time.sleep(1)
    os.system('clear')
    print("Đã tạo VPS thành công!")
    print("Địa chỉ IP của bạn là: ")
    run_command('curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE \'s/.*public_url":"tcp:..([^"]*).*/\1/p\'')
    print(" ")
    print(" ")
    print("Đang kiểm tra kết nối mạng")
    run_command('speedtest-cli')
    print(" ")
    print("VPS sẽ hoạt động được 50h")
    print("________________________________________")
    print("|        Lệnh được viết bởi VinZ.      |")
    print("|______________________________________|")
    print("Hoạt động trên VPS: ")
    run_command('sudo qemu-system-x86_64 -m 12G -cpu host -boot order=c -drive file=link.iso,media=cdrom -drive file=win.img,format=raw -device usb-ehci,id=usb,bus=pci.0,addr=0x4 -device usb-tablet -vnc :0 -smp cores=4 -device rtl8139,netdev=n0 -netdev user,id=n0 -vga qxl -accel kvm -bios bios64.bin')
    os.system('clear')
    print("-------------- Lỗi ----------------")
    print("Ôi không!")
    print("VPS đã dừng hoạt động ")
    print("Xin lỗi vì điều này ")
    print("-----------------------------------")
    print("Lệnh được viết bởi VinZ")
    print("github.com/vinzcyun")
    print(" ")
    print(" ")
    os.system('clear')

    while True:
        print("Đang cố gắng kết nối lại")
        time.sleep(1)
        print("Đang xử lý...")
        time.sleep(1)
        print("Đã kết nối")
        print("Địa chỉ IP truy cập của bạn sẽ vẫn như cũ")
        run_command('sudo qemu-system-x86_64 -m 12G -cpu host -boot order=c -drive file=link.iso,media=cdrom -drive file=win.img,format=raw -device usb-ehci,id=usb,bus=pci.0,addr=0x4 -device usb-tablet -vnc :0 -smp cores=4 -device rtl8139,netdev=n0 -netdev user,id=n0 -vga qxl -accel kvm -bios bios64.bin')
        os.system('clear && sleep 1')
        print("Lỗi không mong muốn")
        time.sleep(2)

if __name__ == "__main__":
    main()
